[project]
name = "curva-s"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastexcel>=0.16.0",
    "matplotlib>=3.10.7",
    "polars>=1.34.0",
    "pyarrow>=21.0.0",
    "seaborn>=0.13.2",
    "xlsxwriter>=3.2.9",
]
